/*
 * Quy Nguyen
 * Dr. Magda Tsintsadze
 * CS635
 * M6 P3 Turtle Interpreter
 * December 7, 2024
 * TurtleInterpreterEnhanced.java
 */

package TurtleInterpreterEnhanced;


import java.io.IOException;
import java.util.List;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import TurtleInterpreterEnhanced.generated.TurtleLexer;
import TurtleInterpreterEnhanced.generated.TurtleParser;

// This is the main class that is used to run the turtle program file. It uses the lexer and parser to create an AST
// and then uses the visitor classes to traverse the AST and execute the turtle program.
// Once the main function completes it displays the total distance traversed by the turtle as well as its net
// distance from the starting point.
public class TurtleInterpreterEnhanced {
    public static void main(String[] args) throws IOException {
        String fileName;
        if (args.length == 0) {
            fileName = "src/main/java/TurtleInterpreterEnhanced/turtleProgramFile.txt";
        } else {
            fileName = args[0];
        }

        // Instantiates a lexer object with a character stream from file named fileName
        TurtleLexer lexer = new TurtleLexer(CharStreams.fromFileName(fileName));
        // Instantiates a CommonTokenStream object with lexer dependency injected
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        // Instantiates a parser object with tokens dependency injected
        TurtleParser parser = new TurtleParser(tokens);
        // Instantiates a ProgramContext which is the root AST generated by the parser
        TurtleParser.ProgramContext program = parser.program();

        // Prints the contents of the AST formed by the parser
        System.out.println("This is the contents of the AST formed by the parser");
        System.out.println(program.toStringTree(parser));

        // Instantiates a MockTurtle object with x, y, and heading set to 0
        Turtle turtle = new MockTurtle(0, 0, 0); {
        }

        // Instantiates a TurtleCommandVisitor object with turtle dependency injected
        TurtleCommandVisitor commandVisitor = new TurtleCommandVisitor(turtle);
        // Instantiates a TurtleMementoVisitor object with turtle dependency injected
        TurtleMementoVisitor mementoVisitor = new TurtleMementoVisitor(turtle);
        // Instantiates a TurtleDistanceVisitor object
        TurtleDistanceVisitor distanceVisitor = new TurtleDistanceVisitor();

        // Visits the program AST with the visitor objects
        commandVisitor.visit(program);
        // Visits the program AST with the visitor objects
        mementoVisitor.visit(program);
        // Visits the program AST with the visitor objects
        distanceVisitor.visit(program);

        // Gets the list of commands, mementos, and distances from the visitor objects
        List<String> commands = commandVisitor.getCommands();
        // Gets the list of mementos from the visitor object
        List<TurtleMemento> mementos = mementoVisitor.getMementos();
        // Gets the list of distances from the visitor object
        List<Double> distances = distanceVisitor.getTotalDistances();

        // Prints the composite list of commands, mementos, and distances
        System.out.println("This is the composite list of commands, mementos, and distances:");
        for (int i = 0; i < commands.size(); i++) {
            String command = commands.get(i);
            TurtleMemento memento = mementos.get(i);
            double distance = distances.get(i);
            System.out.println("Command: " + command + " | Memento - (" + memento.getX() + "," + memento.getY() + "," +
                    memento.getHeading() + ") | Distance: " + distance);
        }

        // Prints some text to the console regarding the total and net distance traveled by the turtle
        System.out.println("This is the total and net distance traveled by the turtle");
        // Prints the total distance traveled by the turtle
        System.out.println("Total distance traveled: " + distanceVisitor.getTotalDistance());
        // Prints the net distance traveled by the turtle
        System.out.println("Net distance traveled: " + mementoVisitor.getNetDistance());
    }
}